spring.datasource.url=jdbc:h2:mem:examdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=uneCleTresLonguePourHS512_1234567890123456789012345678901234567890
jwt.expiration.ms=86400000

logging.level.org.springframework.security=DEBUG